import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@components/Footer";
import NavBar from "@components/NavBar";
import { BackgroundBeams } from "@components/ui/background-beams";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{
          backgroundColor: "#16161A",
          backgroundSize: "cover",
          backgroundPosition: "center",
          margin: 0,
          padding: 0,
          height: "100%",
          width: "100%",
          position: "relative",
        }}
      >
        <header className="relative z-20">
          <NavBar />
        </header>
        <div className="z-20 relative ">{children}</div>
        <BackgroundBeams />
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
